spring:
    application:
        name: application_service 
    datasource:
        url: jdbc:postgresql://localhost:5432/
        username: postgres
        password: pgadmin5
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

server:
    port: 8080
    error.include-message: always

management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true